version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: roni
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: project_db
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
